# Generated by Django 5.2.1 on 2025-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_no', models.CharField(max_length=20, unique=True)),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('grade', models.CharField(max_length=10)),
                ('parent_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
