# Generated by Django 5.2.1 on 2025-05-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('section', models.CharField(choices=[('W', 'W'), ('B', 'B'), ('G', 'G'), ('R', 'R')], max_length=1)),
                ('date_joined', models.DateField()),
                ('current_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_contact',
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parents.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.grade'),
        ),
    ]
