# Generated by Django 5.2.1 on 2025-06-17 09:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_academicyear_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='fee',
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='form',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='form',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_form',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='form',
        ),
        migrations.AlterUniqueTogether(
            name='studentexamresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentexamresult',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='studentexamresult',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentexamresult',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='teacher',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='exam_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='admission_date',
            new_name='date_of_admission',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='hire_date',
            new_name='date_hired',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='term',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='children',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='relationship_to_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='upi_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(to='core.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('cat', 'CAT'), ('midterm', 'Mid-Term'), ('endterm', 'End-Term'), ('kcse', 'KCSE Mock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='core.subject'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form', models.PositiveIntegerField(choices=[(1, 'Form 1'), (2, 'Form 2'), (3, 'Form 3'), (4, 'Form 4')])),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.class'),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=2)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
        ),
        migrations.AddField(
            model_name='feepayment',
            name='fee_structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.feestructure'),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='class',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stream'),
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject', 'class_obj', 'academic_year')},
            },
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='StudentExamResult',
        ),
        migrations.DeleteModel(
            name='StudentSubject',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'stream', 'form')},
        ),
    ]
