# Generated by Django 5.2.1 on 2025-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('bursar', 'Bursar'), ('principal', 'Principal'), ('admin', 'Admin'), ('parent', 'Parent'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=20, null=True),
        ),
    ]
